#!/bin/sh
set -e
# Automatically added by dh_apache2/UNDECLARED
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in netdata  ; do
				apache2_invoke disconf $conf  || exit 1
			done
		fi
	fi
fi
# End automatically added section
