#!/bin/sh

set -e

case "${1}" in
	purge)
		# removing directory overrides
		for DIRECTORY in /var/cache/netdata /var/lib/netdata
		do
			if dpkg-statoverride --list | grep -qw "${DIRECTORY}"
			then
				dpkg-statoverride --remove "${DIRECTORY}"
			fi
		done

		# removing user
		if getent passwd netdata > /dev/null 2>&1
		then
			userdel netdata || echo "Unable to remove netdata user"
		fi

		# removing group
		if getent group netdata > /dev/null 2>&1
		then
			groupdel netdata || echo "Unable to remove netdata group"
		fi

		# removing directories
		rm -rf /var/cache/netdata /var/lib/netdata /var/log/netdata
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installdeb/13.11.4+rb9
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/gunicorn_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/nginx_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+rb9
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+rb9
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'netdata.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
