#!/bin/sh

set -e

case "${1}" in
	configure)
		# creating group
		if ! getent group netdata > /dev/null 2>&1
		then
			 groupadd --system netdata
		fi

		# creating user
		if ! getent passwd netdata > /dev/null 2>&1
		then
			useradd --system -g netdata --home-dir /var/lib/netdata --no-create-home netdata
			mkdir -p /var/lib/netdata
		fi

		# in some plugins netdata must be able to read logfiles
		usermod -G adm netdata

		# creating directory overrides
		for DIRECTORY in /var/cache/netdata /var/lib/netdata
		do
			mkdir -p "${DIRECTORY}"

			if ! dpkg-statoverride --list "${DIRECTORY}" > /dev/null 2>&1
			then
				dpkg-statoverride --update --add netdata netdata 0755 "${DIRECTORY}"
			fi
		done

		# handling plugin capabilities (or setuid as fallback)
		chown -R root:netdata /usr/lib/netdata/plugins.d
		setcap cap_dac_read_search,cap_sys_ptrace+ep /usr/lib/netdata/plugins.d/apps.plugin || \
			chmod 4754 /usr/lib/netdata/plugins.d/apps.plugin

		# handling log owner and permissions
		chown netdata:adm /var/log/netdata
		chmod 2750 /var/log/netdata
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installdeb/13.11.4+rb9
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/gunicorn_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/nginx_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+rb9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'netdata.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'netdata.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'netdata.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'netdata.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4+rb9
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'netdata.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
