#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4+rb9
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/gunicorn_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/nginx_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
# End automatically added section
