#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.4+rb9
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'netdata.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.4+rb9
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/gunicorn_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
dpkg-maintscript-helper rm_conffile /etc/netdata/python.d/nginx_log.conf 1.8.0\+dfsg-1\~ netdata -- "$@"
# End automatically added section
