#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

. /etc/rc.subr

name=netdata
rcvar=netdata_enable

piddir="/var/run/netdata"
pidfile="${piddir}/netdata.pid"

command="/usr/sbin/netdata"
command_args="-P ${pidfile}"

required_files="/etc/netdata/netdata.conf"

start_precmd="netdata_prestart"
stop_postcmd="netdata_poststop"

extra_commands="reloadhealth savedb"

reloadhealth_cmd="netdata_reloadhealth"
savedb_cmd="netdata_savedb"

netdata_prestart()
{
	[ ! -d "${piddir}" ] && mkdir -p "${piddir}"
	chown nobody:nobody "${piddir}"
	return 0
}

netdata_poststop()
{
	[ -f "${pidfile}" ] && rm "${pidfile}"
	return 0
}

netdata_reloadhealth()
{
    p=`cat ${pidfile}`
    kill -USR2 ${p} && echo "Sent USR2 (reload health) to pid ${p}"
    return 0
}

netdata_savedb()
{
    p=`cat ${pidfile}`
    kill -USR2 ${p} && echo "Sent USR1 (save db) to pid ${p}"
    return 0
}

load_rc_config $name
run_rc_command "$1"
